version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/config/fulcio/fulcio"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/config/rekor/rekor"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/config/trillian/trillian-log-server"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/config/trillian/trillian-log-signer"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/config/tsa/tsa"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/argocd"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/audit"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/bastion"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/ca"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/ctlog"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/dex"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/external_secrets"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/fulcio"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/gke_cluster"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/monitoring"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/monitoring/dex"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/monitoring/fulcio"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/monitoring/infra"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/monitoring/prober"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/monitoring/rekor"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/monitoring/slo"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/mysql-shard"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/mysql"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/network"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/oslogin"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/project_roles"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/redis"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/rekor"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/sigstore"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/timestamp"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
- package-ecosystem: "terraform"
  directory: "/terraform/gcp/modules/tuf"
  schedule:
    interval: weekly
  groups:
    terraform:
      patterns:
        - "*"
