---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsa
  namespace: tsa-system
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: tsa-system
  name: tsa
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      serviceAccountName: tsa
      containers:
      - name: tsa
        # Resolved via crane digest 2023-07-16 for v1.1.1
        image: ghcr.io/sigstore/timestamp-server@sha256:b0be2fb18150bcbfe15ff82d95bd9373a5ac7e6d8c7663299940a78e43fe69aa
        ports:
        - containerPort: 3000
        args: [
          "serve",
          "--timestamp-signer=file",
          "--file-signer-key-path=/var/run/tsa-secrets/signing-secret",
          "--file-signer-passwd=$(SECRET_SIGNING_PWD)",
          "--certificate-chain-path=/var/run/tsa-secrets/cert-chain"
        ]
        env:
        - name: SECRET_SIGNING_PWD
          valueFrom:
            secretKeyRef:
              name: tsa-cert-chain
              key: signing-secret-password
        volumeMounts:
        - name: tsa-secrets
          mountPath: "/var/run/tsa-secrets"
          readOnly: true
      volumes:
      - name: tsa-secrets
        secret:
          secretName: tsa-cert-chain
          items:
          - key: signing-secret
            path: signing-secret
          - key: cert-chain
            path: cert-chain
